repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: debug-statements
      - id: mixed-line-ending
        args: [ '--fix=lf' ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        args: [ '--fix' ]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.22  # Use the latest uv-pre-commit version
    hooks:
      - id: uv-audit

  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest-coverage
        entry: python -m pytest --cov=app --cov-fail-under=90
        language: system
        pass_filenames: false
        always_run: true
      - id: mutation-testing
        name: mutmut mutation testing
        entry: mutmut run
        language: system
        stages: [ pre-push ]
        pass_filenames: false
        always_run: true
